spring.config.activate.on-profile=prod
spring.datasource.url=jdbc:mysql://mysql-3f077388-sahayamajose-dfff.j.aivencloud.com:23469/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=${AIVEN_DB_PASSWORD}
